#' Write institutional fetch manifest CSV
#'
#' @param entries Data frame or list of manifest rows.
#' @param path Output CSV path.
#' @export
ingest_write_manifest <- function(entries, path) {
  if (is.list(entries) && !is.data.frame(entries)) {
    entries <- ingest_entries_to_df(entries)
  }
  dir.create(dirname(path), recursive = TRUE, showWarnings = FALSE)
  utils::write.csv(entries, path, row.names = FALSE, na = "")
  invisible(path)
}

#' Read manifest CSV
#'
#' @param path CSV path.
#' @return Data frame.
#' @export
ingest_read_manifest <- function(path) {
  df <- utils::read.csv(path, stringsAsFactors = FALSE, na.strings = "")
  if ("pmid" %in% names(df)) df$pmid <- as.character(df$pmid)
  df
}

#' Generate standalone institutional fetch R script
#'
#' Writes a script intended to run on a VPN-enabled work laptop. The script
#' loads LibeRary and calls [ingest_fetch_institutional()].
#'
#' @param manifest_path Path to manifest CSV.
#' @param output_path Path for generated R script.
#' @param config_path Optional YAML config path embedded in script.
#' @export
ingest_generate_fetch_script <- function(
    manifest_path,
    output_path = "library_fetch_institutional.R",
    config_path = NULL) {
  manifest_path <- normalizePath(manifest_path, winslash = "/", mustWork = FALSE)
  cfg_line <- if (!is.null(config_path) && nzchar(config_path)) {
    sprintf('cfg <- ingest_load_config("%s")', normalizePath(config_path, winslash = "/", mustWork = FALSE))
  } else {
    'cfg <- ingest_load_config(Sys.getenv("LIBERARY_CONFIG", ""))'
  }

  script <- c(
    "#!/usr/bin/env Rscript",
    "# Generated by LibeRary - run on the institutional/VPN network used for article access.",
    "# Usage: Rscript library_fetch_institutional.R",
    "",
    "if (!requireNamespace(\"LibeRary\", quietly = TRUE)) {",
    "  if (requireNamespace(\"devtools\", quietly = TRUE)) {",
    "    devtools::load_all(\".\")",
    "  } else {",
    "    stop(\"Install or load LibeRary before running this script.\")",
    "  }",
    "} else {",
    "  library(LibeRary)",
    "}",
    "",
    cfg_line,
    sprintf("manifest <- \"%s\"", manifest_path),
    "",
    "res <- ingest_fetch_institutional(manifest, cfg = cfg)",
    "print(res$summary)",
    "if (length(res$failures)) {",
    "  message(\"Some downloads failed -- see fetch log in data_dir/logs.\")",
    "}",
    ""
  )

  writeLines(script, output_path)
  invisible(output_path)
}
